[package]
name = "testRsnarkRust"
version = "0.1.0"
edition = "2024"

[dependencies]
rsnark-provers-gnark = "0.1.0"
ark-bn254 = "0.4.0"
ark-groth16 = "0.4.0"
ark-snark = "0.4.0"
ark-serialize = "0.4.0"
